### ISSUE TITLE
ffx_fsr2_accumulate_pass_16bit_permutations_0_0_1_1_0_1.h is missing

### ISSUE THREAD

**Issue by cdozdil** [metarutaiga/FidelityFX-SDK-DX11#1]
Hello,

I wanted to check if FSR2 is compiling or not and got "ffx_fsr2_accumulate_pass_16bit_permutations_0_0_1_1_0_1" entry point not found error. I don't know how complete FSR2 is but would be nice if we can check it.

Thanks for the effort 👍

**Comment by metarutaiga** [comment]
It must run its batch file and compile hlsl files first.

For example: ffx_fsr2_pass_permutations.bat
https://github.com/metarutaiga/FidelityFX-SDK-DX11/blob/master/FidelityFX/host/backends/blob_accessors/permutations/ffx_fsr2_pass_permutations.bat

**Comment by cdozdil** [comment]
As you suggested, I have cleaned generated files and run the batch file again. It created all needed headers and able to compile it. 

Thanks so much.
