### ISSUE TITLE
FSR2 DirectX11 

### ISSUE THREAD

**Issue by cdozdil** [metarutaiga/FidelityFX-SDK-DX11#2]
Hello,

After last issue i have compiled DX11 FSR2 and incorprated it my project but there is catch which i would like to get an advise with your expertise. I am developing a DLSS2XeSS & FSR library which acts like DLSS, takes DLSS inputs and upscales them with FSR or XeSS. For Dx11 there is not so many options and I have already tried DX12 with DX11 but not so performant. That's why i wanted to implement your version of native DX11 FSR2. Problem is if I run it natively it just gives me black screen as output but if I run it with dxvk dll's it gives me output but image is weird (like motion blurry). Black output happens with Unity plugin source of DX11 FSR2 too but dxvk it fuctions normally. Could you give me any hints for correcting this issue? 

Thanks for your time!

If you are interested, DX11 test branch of my library is [here](https://github.com/cdozdil/CyberXeSS/tree/fsr3-dx11)

And this is how it looks with dxvk dll's: 

<video src='https://github.com/metarutaiga/FidelityFX-SDK-DX11/assets/35529761/65d19ad7-94df-4004-b6fe-755159af57e0' width=320></video>

Edit: Behavior feels like motion vectors are missing to me but it's provided by game.

**Comment by metarutaiga** [comment]
Does the motion vectors is canceled jitter vector already?
You may tried FFX_FSR2_ENABLE_MOTION_VECTORS_JITTER_CANCELLATION
(But I tested it, it's worse than canceled jitter motion vectors texture)

Another problem maybe the auto exposure is not correct.
You need use RenderDoc to know what problem is.
(it need to disable Direct3D11.1 when using RenderDoc)
https://github.com/metarutaiga/FidelityFX-SDK-DX11/blob/5de0f8e07bc99cc5e50fa94b4920927653aaf761/FidelityFX/host/backends/dx11/ffx_dx11.cpp#L684

I implemented the FSR2 / FSR3 in my games is very painful, It's not easy to use.

**Comment by cdozdil** [comment]
All these parameters coming from DLSS API actually, after adding a check and fix to the BindingState of Color texture, I made Unity implementation of Dx11 backend work actually but it would be nice to stay on current versions of FSR. 

Thanks for feedback!
